
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smbms?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false
#    prefix:
#     classpath: /templates/
#    suffix: .html

# mybatis showsql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
